### ISSUE TITLE
Hardcoded Path in src/CMakeLists.txt

### ISSUE THREAD

**Issue by lesharris** [wasspaul/sig_gen#1]
There is a hardcoded path in src/CMakeLists.txt that prevents building the project on a system without that directory structure:

```cmake
	pico_generate_pio_header(sig_gen /home/pi/Documents/pico/paulsProjects/sig_gen/manchester_encoding.pio)
```

A simple update to fix this is to use CMAKE_CURRENT_LIST_DIR instead:

```cmake
	pico_generate_pio_header(sig_gen ${CMAKE_CURRENT_LIST_DIR}/manchester_encoding.pio)
```

I can open a PR if you would prefer but it is a quick edit.  Also, thank you very much for this project!

**Comment by wasspaul** [comment]
Thanks for your correction.  I will fix it on my build system, verify it works for me and update GitHub (I will also fix some  typos in the read me).
